[2024-10-09T11:49:59.078+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-09T11:49:59.352+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawl_to_kafka.extract__2 scheduled__2024-10-08T00:00:00+00:00 [queued]>
[2024-10-09T11:49:59.504+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawl_to_kafka.extract__2 scheduled__2024-10-08T00:00:00+00:00 [queued]>
[2024-10-09T11:49:59.505+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-09T11:49:59.739+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): extract__2> on 2024-10-08 00:00:00+00:00
[2024-10-09T11:49:59.836+0000] {standard_task_runner.py:72} INFO - Started process 7792 to run task
[2024-10-09T11:49:59.874+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'crawl_to_kafka', 'extract__2', 'scheduled__2024-10-08T00:00:00+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/crawl_to_kafka.py', '--cfg-path', '/tmp/tmp5x30nh1e']
[2024-10-09T11:49:59.941+0000] {standard_task_runner.py:105} INFO - Job 104: Subtask extract__2
[2024-10-09T11:50:00.720+0000] {task_command.py:467} INFO - Running <TaskInstance: crawl_to_kafka.extract__2 scheduled__2024-10-08T00:00:00+00:00 [running]> on host 2a293f7fa826
[2024-10-09T11:50:01.685+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crawl_to_kafka' AIRFLOW_CTX_TASK_ID='extract__2' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-08T00:00:00+00:00'
[2024-10-09T11:50:01.697+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-09T11:50:01.740+0000] {logging_mixin.py:190} INFO - Start extracting from CAFE
[2024-10-09T11:50:01.795+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=172.17.0.1:9092 <connecting> [IPv4 ('172.17.0.1', 9092)]>: connecting to 172.17.0.1:9092 [('172.17.0.1', 9092) IPv4]
[2024-10-09T11:50:01.798+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-09T11:50:01.805+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=172.17.0.1:9092 <connecting> [IPv4 ('172.17.0.1', 9092)]>: Connection complete.
[2024-10-09T11:50:01.946+0000] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2024-10-09T11:50:01.948+0000] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2024-10-09T11:50:01.955+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-09T11:50:02.111+0000] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2024-10-09T11:50:02.117+0000] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2024-10-09T11:50:02.198+0000] {conn.py:380} INFO - <BrokerConnection node_id=0 host=my-backup-vm-20241006-023353.asia-east1-a.c.modern-environs-436110-t9.internal:9092 <connecting> [IPv4 ('10.0.0.2', 9092)]>: connecting to my-backup-vm-20241006-023353.asia-east1-a.c.modern-environs-436110-t9.internal:9092 [('10.0.0.2', 9092) IPv4]
[2024-10-09T11:50:02.202+0000] {conn.py:1205} INFO - Probing node 0 broker version
[2024-10-09T11:50:02.221+0000] {conn.py:410} INFO - <BrokerConnection node_id=0 host=my-backup-vm-20241006-023353.asia-east1-a.c.modern-environs-436110-t9.internal:9092 <connecting> [IPv4 ('10.0.0.2', 9092)]>: Connection complete.
[2024-10-09T11:50:02.227+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=172.17.0.1:9092 <connected> [IPv4 ('172.17.0.1', 9092)]>: Closing connection. 
[2024-10-09T11:50:02.371+0000] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2024-10-09T11:50:02.372+0000] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2024-10-09T11:50:02.413+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/crawl_to_kafka.py", line 45, in extract
    admin_client.create_topics(new_topics=[topic], validate_only=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/admin/client.py", line 461, in create_topics
    return self._send_request_to_controller(request)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/admin/client.py", line 407, in _send_request_to_controller
    raise error_type(
kafka.errors.TopicAlreadyExistsError: [Error 36] TopicAlreadyExistsError: Request 'CreateTopicsRequest_v3(create_topic_requests=[(topic='stock_data', num_partitions=1, replication_factor=1, replica_assignment=[], configs=[])], timeout=30000, validate_only=False)' failed with response 'CreateTopicsResponse_v3(throttle_time_ms=0, topic_errors=[(topic='stock_data', error_code=36, error_message="Topic 'stock_data' already exists.")])'.
[2024-10-09T11:50:02.519+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=crawl_to_kafka, task_id=extract__2, run_id=scheduled__2024-10-08T00:00:00+00:00, execution_date=20241008T000000, start_date=20241009T114959, end_date=20241009T115002
[2024-10-09T11:50:02.749+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-09T11:50:02.778+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 104 for task extract__2 ([Error 36] TopicAlreadyExistsError: Request 'CreateTopicsRequest_v3(create_topic_requests=[(topic='stock_data', num_partitions=1, replication_factor=1, replica_assignment=[], configs=[])], timeout=30000, validate_only=False)' failed with response 'CreateTopicsResponse_v3(throttle_time_ms=0, topic_errors=[(topic='stock_data', error_code=36, error_message="Topic 'stock_data' already exists.")])'.; 7792)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/crawl_to_kafka.py", line 45, in extract
    admin_client.create_topics(new_topics=[topic], validate_only=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/admin/client.py", line 461, in create_topics
    return self._send_request_to_controller(request)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/admin/client.py", line 407, in _send_request_to_controller
    raise error_type(
kafka.errors.TopicAlreadyExistsError: [Error 36] TopicAlreadyExistsError: Request 'CreateTopicsRequest_v3(create_topic_requests=[(topic='stock_data', num_partitions=1, replication_factor=1, replica_assignment=[], configs=[])], timeout=30000, validate_only=False)' failed with response 'CreateTopicsResponse_v3(throttle_time_ms=0, topic_errors=[(topic='stock_data', error_code=36, error_message="Topic 'stock_data' already exists.")])'.
[2024-10-09T11:50:02.977+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-09T11:50:03.160+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
